# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2021 NOI Techpark <info@noi.bz.it>


# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

stages:
  - test
  - dockerize

include:
 - project: 'OSTC/infrastructure/pipelines'
   file: 'reuse.yaml'

.pythonreq:
  stage: test
  only: [ branches, tags, merge_requests ]  # Add this, because merge requests are not triggered by default
  tags: [ soldaprod, docker, minimal ]
  image: python:3.8
  script:
    - pip install python-dotenv pytype setuptools wheel
    - pip install .
    - python -c "from flanker.addresslib import address" >/dev/null 2>&1

pytype:
  extends: .pythonreq
  script:
    - !reference [ .pythonreq, script ]
    - pytype --config pytype.cfg aliens4friends

unittests:
  extends: .pythonreq
  script:
    - !reference [ .pythonreq, script ]
    - python -m unittest discover aliens4friends/tests/

reuse:
  stage: test
  extends: .reuse
  only: [ branches, tags, merge_requests ]

.dockerize:
  tags: [ soldaprod, docker, minimal ]
  stage: dockerize
  image: docker:20.10

  # Run this job automatically, when we are on the main branch
  # or manual, when triggered on any other branch...
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

  variables:
    CI_REGISTRY_BASE: $CI_REGISTRY/oss-compliance/toolchain/aliens4friends
  before_script:
    - apk update && apk add --no-cache git
  script:
    - CI_REGISTRY_IMAGE=$CI_REGISTRY_BASE/$REGISTRY_NAME
    - echo -n $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - |
      if [ -n "$TINFOILHAT" ]; then
        export GIT_COMMIT="$(git ls-remote https://git.ostc-eu.org/oss-compliance/toolchain/tinfoilhat.git  HEAD | cut -f 1)"
        docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest --build-arg GIT_REF="$GIT_COMMIT" . -f $DOCKERFILE
      else
        docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest . -f $DOCKERFILE
      fi
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest . -f $DOCKERFILE
    - docker push $CI_REGISTRY_IMAGE:latest
  needs:
    - pytype
    - reuse
    - unittests

dockerize toolchain:
  extends: .dockerize
  variables:
    REGISTRY_NAME: toolchain
    DOCKERFILE: infrastructure/docker/toolchain.dockerfile

dockerize yoctobuild:
  extends: .dockerize
  variables:
    REGISTRY_NAME: yoctobuild
    DOCKERFILE: infrastructure/docker/yoctobuild.dockerfile
    TINFOILHAT: "yes"
