#!/bin/bash
# SPDX-License-Identifier: CC0-1
# SPDX-FileCopyrightText: 2021 NOI Techpark <p.moser@noi.bz.it>

### Installation:
# wget -P /usr/local/lib https://github.com/spdx/tools/releases/download/v2.2.5/spdx-tools-2.2.5-jar-with-dependencies.jar

java -jar /usr/local/lib/spdx-tools-2.2.5-jar-with-dependencies.jar
