  version: 2.0-alpha
  oe_init_build_env_dir: oe-core
  common_configs:
    - SSTATE_DIR = "/build/common/sstate-cache"
    - DL_DIR = "/build/common/downloads"
    - SSTATE_MIRRORS = "file://.* file:///ostc/common/bitbake/sstate-cache/PATH"
    - INHERIT += "own-mirrors"
    - SOURCE_MIRROR_URL = "file:///ostc/common/bitbake/downloads"
    - INHERIT += "cve-check"
    - INHERIT += "rm_work"
  build_matrix:
    - TEMPLATECONF: ../meta-openharmony/conf
      image: ipcamera
      env:
        DISTRO:
          - openharmony-v1
          - openharmony-v3
        MACHINE: hispark-aries
    - TEMPLATECONF: ../oniro/flavours/linux
      image:
        - oniro-image-base
        - oniro-image-base-dev
        - oniro-image-base-tests
        - oniro-image-extra
        - oniro-image-extra-dev
        - oniro-image-extra-tests
      env:
        MACHINE:
          - qemux86-64
          - qemux86
          - stm32mp1-av96
          - raspberrypi4-64
    - TEMPLATECONF: ../oniro/flavours/linux
      image:
        - oniro-image-base
        - oniro-image-base-tests
        - oniro-image-extra
        - oniro-image-extra-tests
      env:
          MACHINE: seco-intel-b68
          CONFIG_SERIAL_OF_PLATFORM: y
    - TEMPLATECONF: ../oniro/flavours/linux
      image:
        - oniro-image-base
        - oniro-image-base-tests
        - oniro-image-extra
        - oniro-image-extra-tests
      env:
        MACHINE: seco-imx8mm-c61
        ACCEPT_FSL_EULA: "1"
