  version: 1.1
  common_configs:
    - SSTATE_DIR ?= "/build/common/sstate-cache"
    - DL_DIR ?= "/build/common/downloads"
    - SSTATE_MIRRORS ?= "file://.* file:///ostc/common/bitbake/sstate-cache/PATH"
    - INHERIT += "own-mirrors"
    - SOURCE_MIRROR_URL = "file:///ostc/common/bitbake/downloads"
    - INHERIT += "cve-check"
  flavours:
    linux:
      machines:
        - qemux86-64
        - qemux86
        - seco-intel-b68
        - stm32mp1-av96
        - seco-imx8mm-c61
        - raspberrypi4-64
      images:
        - oniro-image-base
        - oniro-image-base-dev
        - oniro-image-base-tests
        - oniro-image-extra
        - oniro-image-extra-dev
        - oniro-image-extra-tests
      configs:
        seco-intel-b68:
          - CONFIG_SERIAL_OF_PLATFORM = "y"
        seco-imx8mm-c61:
          - ACCEPT_FSL_EULA = "1"
    zephyr:
      machines:
        - qemu-x86
        - qemu-cortex-m3
        - 96b-nitrogen
        - 96b-avenger96
        - nrf52840dk-nrf52840
        - arduino-nano-33-ble
      images:
        - zephyr-philosophers
    freertos:
      machines:
        - qemuarmv5
      images:
        - freertos-demo

