name: CI/CD

on:
  push:
  pull_request:

env:
  PROJECT_NAME: solda
  DOCKER_REGISTRY_HOST: ghcr.io
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
  DOCKER_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose -f docker-compose.yml build    

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_FOSSOLOGY_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
          X_LOG_LEVEL: debug
          X_FOSSOLOGY_DB_HOST: test-pg-bdp.co90ybcr8iim.eu-west-1.rds.amazonaws.com
          X_FOSSOLOGY_DB_NAME: alien4friends
          X_FOSSOLOGY_DB_USER: alien4friends
          X_FOSSOLOGY_DB_PASSWORD: ${{ secrets.FOSSOLOGY_DB_PASSWORD }}
          X_FOSSOLOGY_SERVER_PORT: 1010

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./infrastructure/docker/fossology

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}

  # NO PROD AVAILABLE YET
  # deploy-prod:
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/prod'
  #   needs: test
  #   concurrency: deploy-prod
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v2

  #     - name: Create .env file
  #       uses: noi-techpark/github-actions/env-file@v2
  #       env:
  #         X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
  #         X_DOCKER_FOSSOLOGY_IMAGE: ${{ env.DOCKER_IMAGE }}
  #         X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
  #         X_LOG_LEVEL: debug
  #         X_FOSSOLOGY_DB_HOST: test-pg-bdp.co90ybcr8iim.eu-west-1.rds.amazonaws.com
  #         X_FOSSOLOGY_DB_NAME: alien4friends
  #         X_FOSSOLOGY_DB_USER: alien4friends
  #         X_FOSSOLOGY_DB_PASSWORD: ${{ secrets.FOSSOLOGY_DB_PASSWORD }}
  #         X_FOSSOLOGY_SERVER_PORT: 1010

  #     - name: Build and push 
  #       uses: noi-techpark/github-actions/docker-build-and-push@v2
  #       with:
  #         docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
  #         docker-username: ${{ github.actor }}
  #         docker-password: ${{ secrets.GITHUB_TOKEN }}
  #         working-directory: ./infrastructure/docker/fossology

  #     - name: Deploy application
  #       uses: noi-techpark/github-actions/docker-deploy@v2
  #       with:
  #         hosts: 'prod'
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
  #         docker-username: 'noi-techpark-bot'
  #         docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  #         project-name: ${{ env.PROJECT_NAME }}